### ISSUE TITLE
Change package and namespace to `Java` rather than `IdrisJava`.

### ISSUE THREAD

**Issue by jfdm** [idris-hackers/idris-java#5]
Question: Would it not be better to call the package `java`? As we are already in Idris, the Idris in the `IdrisJava` namespace seems a little redundant. 

If I have time I shall make the alterations myself and issue a PR, but thought it worth a mention in case anybody agrees and wishes to contribute a PR. Also I have no idea how this would affect upstream dev..

**Comment by bgaster** [comment]
I would prefer not to change the package name to Java, for two reasons:

1. I followed the naming convention of IdrisScript, the Javascript backend: 
     https://github.com/idris-hackers/IdrisScript
2. In a application I've written for automatically generating FFI interface for Java method prototypes, there is a library for Java  syntax and parsing, packaged under the name Java.

**Comment by jfdm** [comment]
Ah okay. Thought it was worth a mention. Personally, I liked the approach taken in the python backend (ziman/idris-py) where the namespace is `Python` a little bit cleaner.

**Comment by Melvar** [comment]
There should definitely be a convention for the names of backend-FFI libraries. The question is how to come up with one.
